services:

#  hinge-ai-backend-app:
#    build: .
#    container_name: hinge-ai-backend-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mydb
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
